on:
  workflow_dispatch:
  push:
    branches:
      - gh-action-build

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build for Android
    steps:
      - uses: actions/checkout@v3
      - id: build
        uses: ioribranford/docker-build-love-android@11.4
        env:
          ENV_SCRIPT: "make-vars-android.sh"
          ICONS_DIR: "$GITHUB_WORKSPACE/android/app/src/main/res"
          KEYSTORE_FILE: "$GITHUB_WORKSPACE/release.keystore"
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          name: android-builds
          path: |
            ${{ steps.build.outputs.apkNoRecord }}
            ${{ steps.build.outputs.apkRecord }}
            ${{ steps.build.outputs.bundleNoRecord }}
            ${{ steps.build.outputs.bundleRecord }}